Fix issue with non-hyphen negative signs in exp notation, #128
NightOwl888/J2N pull request #129
Opened 2024-12-31 21:58 UTC by paulirwin

Fixes #128

2025-03-08 22:03 UTC, paulirwin commented
@NightOwl888 Reminder about this PR for J2N, needed by Lucene.NET. Thanks!

2025-07-15 12:18 UTC, paulirwin commented
@NightOwl888 Reminder about this PR. I'd like to get this in 2.2.

2025-09-25 10:31 UTC, NightOwl888 requested changes
Thanks for the PR.

I agree this is a bug, but this is not a complete fix.

The "J" format is similar to the "G" format. They switch between fixed and scientific notation depending on magnitude of the number.

## Scientific Format

The negative sign is always placed at the beginning of the number. So, this part is now correct.

## Fixed Format

In this case, the [NumberNegativePattern](https://learn.microsoft.com/en-us/dotnet/api/system.globalization.numberformatinfo.numbernegativepattern?view=net-9.0#remarks) is used to determine the culture-aware formatting of the negative sign.

> The [NumberNegativePattern](https://learn.microsoft.com/en-us/dotnet/api/system.globalization.numberformatinfo.numbernegativepattern?view=net-9.0) property defines the format of negative values formatted with the "N" standard numeric format string. This property has one of the values in the following table. The symbol "-" is the [NegativeSign](https://learn.microsoft.com/en-us/dotnet/api/system.globalization.numberformatinfo.negativesign?view=net-9.0) and n is a number.

Value	| Associated pattern
-----------|---------------------
0	|(n)
1	|-n
2	|- n
3	|n-
4	|n -

> The default value for the invariant culture returned by the [InvariantInfo](https://learn.microsoft.com/en-us/dotnet/api/system.globalization.numberformatinfo.invariantinfo?view=net-9.0) property is 1, which represents "-n", where n is a number.

Microsoft used a [clever format string loop](https://github.com/dotnet/runtime/blob/v6.0.36/src/libraries/System.Private.CoreLib/src/System/Number.Formatting.cs#L2371-L2392) to do this format positioning. However, since we don't have a single method for writing out one digit at a time and the formats can either contain a prefix, suffix, or both, it makes sense to break this into 2 static arrays that we can write to either the prefix or suffix part of the buffer.

```c#
        private static readonly string[] NegativeNumberPrefixFormats =
        {
            "(", "-", "- ", "", "",
        };

        private static readonly string[] NegativeNumberSuffixFormats =
        {
            ")", "", "", "-", " -",
        };
```

Simply pass the `info.NegativeNumberPattern` as the index of the string array to use, then loop through each character. When encountering a literal "-", it should be replaced with `info.NegativeSign` instead in the buffer. Other characters should be written literally to the buffer.

There may be a better way to optimize this that doesn't involve static arrays, though. The options are few and probably won't change, so hard coding in the name of performance is not that big of a deal.

### Buffer Length

The buffer length needs to be adjusted to accommodate any extra characters in the `info.NegativeSign` and `info.NegativeNumberPattern` for the current culture. So, I think the best approach would be to store these localized strings in local variables so their lengths can be used in the buffer length calculation. Then they can be passed into the `WriteBuffer()` method where the pattern can be looped through and `negSign` characters replaced, as necessary. Allocating a few extra characters for padding is not a big deal.

Do note that the default value of `info.NegativeSign` can be replaced by the end user, so in theory the string could be any length.

2025-10-01 20:11 UTC, paulirwin commented
> The buffer length needs to be adjusted to accommodate any extra characters in the info.NegativeSign...

FYI - this was already done in the existing code: https://github.com/NightOwl888/J2N/blob/f92e1b76809ce45a0c8437100ceceb19a527b93a/src/J2N/Numerics/RyuDouble.cs#L1162-L1166

The `negSign` parameter to WriteBuffer was just ignored though for exponential notation, which I assume was an oversight.

I think the NumberNegativePattern change can be broken out as a separate issue, as it is not directly related to this bug, and I believe this PR is a complete fix for the bug as specified. This bug is specifically about exponential notation within the existing code.

2025-10-02 19:56 UTC, NightOwl888 commented
My bad. It seems that the `NegativeNumberPattern` only takes effect on the "N" format, not the "G" (or in this case "J") format. So, this is a complete fix.

2025-10-02 19:57 UTC, merged